### ISSUE TITLE
Can't load volume in 2.6.5

### ISSUE THREAD

**Issue by Raoul-Kima** [nci/drishti#29]
Recently I saw that drishti 2.6.5 has been released. When I try to load a volume dataset it gives me an error and closes. I've been using 2.6.4 so far, and never had this issue with that version.

Steps to reproduce:
1. open drishti
2. file / Load Volume / Load 1 Volume
3. select a drishti volume file. (I verified that the same file loads without problems in 2.6.4, but the file was produced with the import tool that is distributed with 2.6.5)

Here's the contents of the error message:

```
-------------Error----------------

WARNING: 0:37: 'assign' : implicit type conversion allowed from GLSL 1.20 
WARNING: 0:38: 'assign' : implicit type conversion allowed from GLSL 1.20 
WARNING: 0:39: 'assign' : implicit type conversion allowed from GLSL 1.20 
ERROR: 0:85: ')' : syntax error syntax error


-----------Shader---------------

1 : #extension GL_ARB_texture_rectangle : enable
2 : uniform sampler2D lutTex;
3 : uniform sampler2DRect dragTex;
4 : uniform int gridx;
5 : uniform int gridy;
6 : uniform int gridz;
7 : uniform int ncols;
8 : uniform int llod;
9 : uniform int lgridx;
10 : uniform int lgridy;
11 : uniform int lgridz;
12 : uniform int lncols;
13 : uniform bool opshader;
14 : uniform float tfSet;
15 : void main(void)
16 : {
17 :   vec2 tc = gl_TexCoord[0].xy;
18 :   int lcol = int(tc.x)/lgridx;
19 :   int lrow = int(tc.y)/lgridy;
20 :   float x = tc.x - float(lcol*lgridx);
21 :   float y = tc.y - float(lrow*lgridy);
22 :   float z = float(lrow*lncols + lcol);
23 :   vec3 pos = vec3(x,y,z);
24 :   bvec3 pless = lessThan(pos, vec3(1.5,1.5,1.5));
25 :   bvec3 pgret = greaterThan(pos, vec3(float(lgridx)-2.5,float(lgridy)-2.5,float(lgridz)-2.5));
26 :   if (any(pless) || any(pgret)) 
27 :     { gl_FragColor = vec4(0.0,0.0,0.0,0.0); return; }
28 :   float xO = x*float(llod);
29 :   float yO = y*float(llod);
30 :   float zO = z*float(llod);
31 : int alod = llod-1;
32 : vec4 fcolor = vec4(0.0,0.0,0.0,0.0);
33 : for(int xa=-alod; xa<=alod; xa++)
34 : for(int ya=-alod; ya<=alod; ya++)
35 : for(int za=-alod; za<=alod; za++)
36 : {
37 :   float x = xO + xa;
38 :   float y = yO + ya;
39 :   float z = zO + za;
40 :   int row = int(z)/ncols;
41 :   int col = int(z) - row*ncols;
42 :   row *= gridy;
43 :   col *= gridx;
44 :   tc = vec2(float(col)+x, float(row)+y);
45 :   vec2 vg;
46 :   vg.x = texture2DRect(dragTex, tc.xy).x;
47 :   vec3 sample1, sample2;
48 :   float x1 = max(0.0, float(x-1.0));
49 :   sample1.x = texture2DRect(dragTex, vec2(float(col)+x1, float(row)+y)).x;
50 :   x1 = min(float(gridx-1), float(x+1.0));
51 :   sample2.x = texture2DRect(dragTex, vec2(float(col)+x1, float(row)+y)).x;
52 :   float y1 = max(0.0, float(y-1.0));
53 :   sample1.y = texture2DRect(dragTex, vec2(float(col)+x, float(row)+y1)).x;
54 :   y1 = min(float(gridy-1), float(y+1.0));
55 :   sample2.y = texture2DRect(dragTex, vec2(float(col)+x, float(row)+y1)).x;
56 :   int z1 = int(max(0.0, float(z-1.0)));
57 :   row = z1/ncols;
58 :   col = z1 - row*ncols;
59 :   row *= gridy;
60 :   col *= gridx;
61 :   sample1.z = texture2DRect(dragTex, vec2(float(col)+x, float(row)+y)).x;
62 :   z1 = int(min(float(gridz-1), float(z+1.0)));
63 :   row = z1/ncols;
64 :   col = z1 - row*ncols;
65 :   row *= gridy;
66 :   col *= gridx;
67 :   sample2.z = texture2DRect(dragTex, vec2(float(col)+x, float(row)+y)).x;
68 :   vg.y = distance(sample1, sample2);
69 : float val = vg.x;
70 : float grad = vg.y*0.125;
71 : vg.y = tfSet + grad;
72 :  if (opshader)
73 :    {
74 :      float alpha = texture2D(lutTex, vg.xy).a;
75 :      fcolor += vec4(val, grad, alpha, 1.0);
76 :    }
77 :  else
78 :    {
79 :      vec4 clr = texture2D(lutTex, vg.xy);
80 :      clr.rgb *= clr.a;
81 :      clr.a = step(0.01, clr.a);
82 :      fcolor += clr;
83 :    }
84 : }
85 :  gl_FragColor = fcolor/pow(2.0*(float)alod+1, 3.0);
86 : }
87 : 
```

I'm running windows 7 on a laptop using on board graphics (Intel HD graphics 5500).

If I can do anything else to help resolving this issuse I'd be happy to do so.

**Comment by AjayLimaye** [comment]
Hi Raoul,
  Please update the graphics driver.  That should fix the problem.
Cheers,
Ajay

**Comment by Raoul-Kima** [comment]
Hello Ajay,

thanks for the fast response.
I updated the Driver, but the Problem persists.
The device manager says my driver version is now from August 2018. Since I have a Lenovo system, I did the update via the Lenovo system update program, which now sais that there are no newer drivers available. (And I did restart the Computer twice after the Install).

Best Regards,
Raoul

**Comment by AjayLimaye** [comment]
Hi Raoul & Kieran,
  I will be back at work next week, will try to figure out the problem.
Cheers,
Ajay

**Comment by AjayLimaye** [comment]
Please try drishti.exe from here -
http://sf.anu.edu.au/~acl900/drishti_perpetualbeta/2.6.5/drishti.exe
Cheers,
Ajay

**Comment by Raoul-Kima** [comment]
Hi Ajay,

Thanks. I tried it and, at exactly the same point, now get this error:

```
 -------------Error----------------

WARNING: 0:3: '' :  #version directive missing
WARNING: 0:31: 'assign' : implicit type conversion allowed from GLSL 1.20 
ERROR: 0:31: '=' :  cannot convert from 'highp float' to 'highp int'
WARNING: 0:37: 'assign' : implicit type conversion allowed from GLSL 1.20 
WARNING: 0:38: 'assign' : implicit type conversion allowed from GLSL 1.20 
WARNING: 0:39: 'assign' : implicit type conversion allowed from GLSL 1.20 


-----------Shader---------------

1 : #extension GL_ARB_texture_rectangle : enable
2 : uniform sampler2D lutTex;
3 : uniform sampler2DRect dragTex;
4 : uniform int gridx;
5 : uniform int gridy;
6 : uniform int gridz;
7 : uniform int ncols;
8 : uniform int llod;
9 : uniform int lgridx;
10 : uniform int lgridy;
11 : uniform int lgridz;
12 : uniform int lncols;
13 : uniform bool opshader;
14 : uniform float tfSet;
15 : void main(void)
16 : {
17 :   vec2 tc = gl_TexCoord[0].xy;
18 :   int lcol = int(tc.x)/lgridx;
19 :   int lrow = int(tc.y)/lgridy;
20 :   float x = tc.x - float(lcol*lgridx);
21 :   float y = tc.y - float(lrow*lgridy);
22 :   float z = float(lrow*lncols + lcol);
23 :   vec3 pos = vec3(x,y,z);
24 :   bvec3 pless = lessThan(pos, vec3(1.5,1.5,1.5));
25 :   bvec3 pgret = greaterThan(pos, vec3(float(lgridx)-2.5,float(lgridy)-2.5,float(lgridz)-2.5));
26 :   if (any(pless) || any(pgret)) 
27 :     { gl_FragColor = vec4(0.0,0.0,0.0,0.0); return; }
28 :   float xO = x*float(llod);
29 :   float yO = y*float(llod);
30 :   float zO = z*float(llod);
31 : int alod = max(1.0, float(llod)-1.0);
32 : vec4 fcolor = vec4(0.0,0.0,0.0,0.0);
33 : for(int xa=-alod; xa<=alod; xa++)
34 : for(int ya=-alod; ya<=alod; ya++)
35 : for(int za=-alod; za<=alod; za++)
36 : {
37 :   float x = xO + xa;
38 :   float y = yO + ya;
39 :   float z = zO + za;
40 :   int row = int(z)/ncols;
41 :   int col = int(z) - row*ncols;
42 :   row *= gridy;
43 :   col *= gridx;
44 :   tc = vec2(float(col)+x, float(row)+y);
45 :   vec2 vg;
46 :   vg.x = texture2DRect(dragTex, tc.xy).x;
47 :   vec3 sample1, sample2;
48 :   float x1 = max(0.0, float(x-1.0));
49 :   sample1.x = texture2DRect(dragTex, vec2(float(col)+x1, float(row)+y)).x;
50 :   x1 = min(float(gridx-1), float(x+1.0));
51 :   sample2.x = texture2DRect(dragTex, vec2(float(col)+x1, float(row)+y)).x;
52 :   float y1 = max(0.0, float(y-1.0));
53 :   sample1.y = texture2DRect(dragTex, vec2(float(col)+x, float(row)+y1)).x;
54 :   y1 = min(float(gridy-1), float(y+1.0));
55 :   sample2.y = texture2DRect(dragTex, vec2(float(col)+x, float(row)+y1)).x;
56 :   int z1 = int(max(0.0, float(z-1.0)));
57 :   row = z1/ncols;
58 :   col = z1 - row*ncols;
59 :   row *= gridy;
60 :   col *= gridx;
61 :   sample1.z = texture2DRect(dragTex, vec2(float(col)+x, float(row)+y)).x;
62 :   z1 = int(min(float(gridz-1), float(z+1.0)));
63 :   row = z1/ncols;
64 :   col = z1 - row*ncols;
65 :   row *= gridy;
66 :   col *= gridx;
67 :   sample2.z = texture2DRect(dragTex, vec2(float(col)+x, float(row)+y)).x;
68 :   vg.y = distance(sample1, sample2);
69 : float val = vg.x;
70 : float grad = vg.y*0.125;
71 : vg.y = tfSet + grad;
72 :  if (opshader)
73 :    {
74 :      float alpha = texture2D(lutTex, vg.xy).a;
75 :      fcolor += vec4(val, grad, alpha, 1.0);
76 :    }
77 :  else
78 :    {
79 :      vec4 clr = texture2D(lutTex, vg.xy);
80 :      clr.rgb *= clr.a;
81 :      clr.a = step(0.01, clr.a);
82 :      fcolor += clr;
83 :    }
84 : }
85 :  gl_FragColor = fcolor/pow(2.0*float(alod)+1.0, 3.0);
86 : }
87 : 
```

**Comment by AjayLimaye** [comment]
Updated the shader code - Please try again
http://sf.anu.edu.au/~acl900/drishti_perpetualbeta/2.6.5/drishti.exe

**Comment by AjayLimaye** [comment]
Hi Raoul, Kieran,
  Please check whether Drishti is being run on the discrete graphics card
if you have one on your laptop.
Cheers,
Ajay

**Comment by Raoul-Kima** [comment]
Hi Ajay,

I only have onboard graphics (Intel HD graphics 5500). Does that answer your question?
The Processor is an Intel Core i5-5200U.

With the new version still the same behaviour, here's the message:

```
-------------Error----------------

WARNING: 0:3: '' :  #version directive missing
WARNING: 0:22: 'assign' : implicit type conversion allowed from GLSL 1.20 
WARNING: 0:22: 'assign' : implicit type conversion allowed from GLSL 1.20 
ERROR: 0:22: '=' :  cannot convert from 'uniform highp float' to 'highp int'
WARNING: 0:26: 'assign' : implicit type conversion allowed from GLSL 1.20 
WARNING: 0:34: 'assign' : implicit type conversion allowed from GLSL 1.20 
WARNING: 0:35: 'assign' : implicit type conversion allowed from GLSL 1.20 


-----------Shader---------------

1 : #extension GL_ARB_texture_rectangle : enable
2 : uniform sampler2DRect lightTex;
3 : uniform int gridx;
4 : uniform int gridy;
5 : uniform int gridz;
6 : uniform int ncols;
7 : uniform float llod;
8 : uniform int lgridx;
9 : uniform int lgridy;
10 : uniform int lncols;
11 : void main(void)
12 : {
13 :   vec2 tc = gl_TexCoord[0].xy;
14 :   int col = int(tc.x)/gridx;
15 :   int row = int(tc.y)/gridy;
16 :   float x = tc.x - float(col*gridx);
17 :   float y = tc.y - float(row*gridy);
18 :   float z = float(row*ncols + col);
19 :   float xO = x*float(llod);
20 :   float yO = y*float(llod);
21 :   float zO = z*float(llod);
22 : int alod = llod-1;
23 : vec4 fcolor = vec4(0.0,0.0,0.0,0.0);
24 : for(int za=-alod; za<=alod; za++)
25 : {
26 :   float z = zO + za;
27 :   int lrow = int(z)/lncols;
28 :   int lcol = int(z) - lrow*lncols;
29 :   lrow *= lgridy;
30 :   lcol *= lgridx;
31 :   for(int xa=-alod; xa<=alod; xa++)
32 :   for(int ya=-alod; ya<=alod; ya++)
33 :   {
34 :     float x = xO + xa;
35 :     float y = yO + ya;
36 :     vec2 ltc = vec2(float(lcol)+x, float(lrow)+y);
37 :     fcolor += vec4(texture2DRect(lightTex, ltc).rgb, 1.0);
38 :   }
39 : }
40 :  gl_FragColor = fcolor/pow(2.0*float(alod)+1.0, 3.0);
41 : }
42 : 
```

Thanks,
Raoul

**Comment by ZhaoSQ-CH** [comment]
Hello, I also encountered the same problem

The computer configuration：lenovo ideapad 300-15isk Intel(R) HD Graphics 520。


-------------Error----------------

WARNING: 0:3: '' :  #version directive missing
WARNING: 0:37: 'assign' : implicit type conversion allowed from GLSL 1.20 
WARNING: 0:38: 'assign' : implicit type conversion allowed from GLSL 1.20 
WARNING: 0:39: 'assign' : implicit type conversion allowed from GLSL 1.20 
ERROR: 0:85: ')' : syntax error syntax error


-----------Shader---------------

1 : #extension GL_ARB_texture_rectangle : enable
2 : uniform sampler2D lutTex;
3 : uniform sampler2DRect dragTex;
4 : uniform int gridx;
5 : uniform int gridy;
6 : uniform int gridz;
7 : uniform int ncols;
8 : uniform int llod;
9 : uniform int lgridx;
10 : uniform int lgridy;
11 : uniform int lgridz;
12 : uniform int lncols;
13 : uniform bool opshader;
14 : uniform float tfSet;
15 : void main(void)
16 : {
17 :   vec2 tc = gl_TexCoord[0].xy;
18 :   int lcol = int(tc.x)/lgridx;
19 :   int lrow = int(tc.y)/lgridy;
20 :   float x = tc.x - float(lcol*lgridx);
21 :   float y = tc.y - float(lrow*lgridy);
22 :   float z = float(lrow*lncols + lcol);
23 :   vec3 pos = vec3(x,y,z);
24 :   bvec3 pless = lessThan(pos, vec3(1.5,1.5,1.5));
25 :   bvec3 pgret = greaterThan(pos, vec3(float(lgridx)-2.5,float(lgridy)-2.5,float(lgridz)-2.5));
26 :   if (any(pless) || any(pgret)) 
27 :     { gl_FragColor = vec4(0.0,0.0,0.0,0.0); return; }
28 :   float xO = x*float(llod);
29 :   float yO = y*float(llod);
30 :   float zO = z*float(llod);
31 : int alod = llod-1;
32 : vec4 fcolor = vec4(0.0,0.0,0.0,0.0);
33 : for(int xa=-alod; xa<=alod; xa++)
34 : for(int ya=-alod; ya<=alod; ya++)
35 : for(int za=-alod; za<=alod; za++)
36 : {
37 :   float x = xO + xa;
38 :   float y = yO + ya;
39 :   float z = zO + za;
40 :   int row = int(z)/ncols;
41 :   int col = int(z) - row*ncols;
42 :   row *= gridy;
43 :   col *= gridx;
44 :   tc = vec2(float(col)+x, float(row)+y);
45 :   vec2 vg;
46 :   vg.x = texture2DRect(dragTex, tc.xy).x;
47 :   vec3 sample1, sample2;
48 :   float x1 = max(0.0, float(x-1.0));
49 :   sample1.x = texture2DRect(dragTex, vec2(float(col)+x1, float(row)+y)).x;
50 :   x1 = min(float(gridx-1), float(x+1.0));
51 :   sample2.x = texture2DRect(dragTex, vec2(float(col)+x1, float(row)+y)).x;
52 :   float y1 = max(0.0, float(y-1.0));
53 :   sample1.y = texture2DRect(dragTex, vec2(float(col)+x, float(row)+y1)).x;
54 :   y1 = min(float(gridy-1), float(y+1.0));
55 :   sample2.y = texture2DRect(dragTex, vec2(float(col)+x, float(row)+y1)).x;
56 :   int z1 = int(max(0.0, float(z-1.0)));
57 :   row = z1/ncols;
58 :   col = z1 - row*ncols;
59 :   row *= gridy;
60 :   col *= gridx;
61 :   sample1.z = texture2DRect(dragTex, vec2(float(col)+x, float(row)+y)).x;
62 :   z1 = int(min(float(gridz-1), float(z+1.0)));
63 :   row = z1/ncols;
64 :   col = z1 - row*ncols;
65 :   row *= gridy;
66 :   col *= gridx;
67 :   sample2.z = texture2DRect(dragTex, vec2(float(col)+x, float(row)+y)).x;
68 :   vg.y = distance(sample1, sample2);
69 : float val = vg.x;
70 : float grad = vg.y*0.125;
71 : vg.y = tfSet + grad;
72 :  if (opshader)
73 :    {
74 :      float alpha = texture2D(lutTex, vg.xy).a;
75 :      fcolor += vec4(val, grad, alpha, 1.0);
76 :    }
77 :  else
78 :    {
79 :      vec4 clr = texture2D(lutTex, vg.xy);
80 :      clr.rgb *= clr.a;
81 :      clr.a = step(0.01, clr.a);
82 :      fcolor += clr;
83 :    }
84 : }
85 :  gl_FragColor = fcolor/pow(2.0*(float)alod+1, 3.0);
86 : }
87 :

**Comment by AjayLimaye** [comment]
Hi Zhao,
  Please try 2.6.6 (currently beta) from
https://cloudstor.aarnet.edu.au/plus/s/ykqMmmikfXxHxKC
Cheers,
Ajay

**Comment by vincentroy105** [comment]
Hi Ajay,

I've been working with Drishti for all of my master's degree, and I've worked on 2.6.2 and 2.6.3. Recently, I wanted to access this data with either 2.6.3 or even 3.0.0 and also couldn't load any pvl.nc files I created back in the days.

I've tried with my PC which is equipped with latest drivers of a GTX 1080ti and my laptop with also the latest drivers and a RTX 3060.

Thank you

**Comment by AjayLimaye** [comment]
Hi Vincent,
  Please check the Texture Memory Size setting under the Preferences
panel.  Set it to the size of the texture memory you have on your graphics
card.  Default value is very low (128Mb).

In the next update, I have put in a condition to check whether the user has
changed the texture memory size from default value; if not then prompt to
change the value.  Unfortunately, I cannot easily guess the texture memory
size of the graphics card, hence the solution.

Cheers,
Ajay

**Comment by vincentroy105** [comment]
Hi Ajay,

I’m sorry, I deleted the post because I found the issue and it was a previous issue that I brought up back in the days.

It wasn’t loading because the data was on my external hard drive and I can’t get the software to have full permission there apparently, even if it’s all checked!

Putting the data directly in a public document, such as ‘Downloads’, did the trick!

Thank you.

Vincent Roy, M. Sc. Biologie
[Titre : instagram - Description : icône Instagram]<https://www.instagram.com/vinceender/>   [Titre : LinkedIn - Description : Icône LinkedIn] <https://www.linkedin.com/in/vincent-roy-34183121b/>

De : AjayLimaye ***@***.***>
Envoyé : 30 octobre 2022 22:50
À : nci/drishti ***@***.***>
Cc : vincentroy105 ***@***.***>; Comment ***@***.***>
Objet : Re: [nci/drishti] Can't load volume in 2.6.5 (#29)

Hi Vincent,
Please check the Texture Memory Size setting under the Preferences
panel. Set it to the size of the texture memory you have on your graphics
card. Default value is very low (128Mb).

In the next update, I have put in a condition to check whether the user has
changed the texture memory size from default value; if not then prompt to
change the value. Unfortunately, I cannot easily guess the texture memory
size of the graphics card, hence the solution.

Cheers,
Ajay

**Comment by AjayLimaye** [comment]
Cheers.
Ajay
